/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Java_Prime_Test;
import org.junit.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.safari.SafariDriver;

import java.io.File;

import static org.junit.Assert.assertEquals;
public class SeleniumTestPrima
{
    private static WebDriver driver;

    @BeforeClass
    public static void setup()
        {
            //Set file path to the web driver
            File chrome = new File("src/test/resources/chromedriver");
            System.setProperty("webdriver.chrome.driver", chrome.getAbsolutePath());

            //Created an instance of the driver we need
            driver = new ChromeDriver();
        }

    @Test
    public void toSite()
        {
            //Navigate to a website in the browser driver
            driver.get("https://www.instagram.com");

            //Test to make sure the title of the page is what it should be
            String pageTitle = driver.getTitle();

            assertEquals("Instagram", pageTitle);
        }

    @Test
     public void wikiWorks()
        {
            //Navigate to website
            driver.get("https://www.wikipedia.org");
            //Click on the English link
            WebElement eng = driver.findElement(By.id("js-link-box-en"));
            eng.click();
            //Verify that we made it to the random page by using title
            assertEquals("Wikipedia, the free encyclopedia", driver.getTitle());

        }

     @AfterClass
      public static void teardown()
         {
             driver.quit();
         }
}
